package net.geoprism.registry.action.geoobject;

@com.runwaysdk.business.ClassSignature(hash = 1700216042)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AttributeAction.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class AttributeActionQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
private static final long serialVersionUID = 1700216042;

  protected AttributeActionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.action.geoobject.AttributeActionDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.action.geoobject.AttributeActionDTO>)super.getResultSet();
}
}
