package net.geoprism.registry.action.geoobject;

@com.runwaysdk.business.ClassSignature(hash = -777410573)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GeoObjectAction.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  class GeoObjectActionQuery extends net.geoprism.registry.action.AbstractActionQuery

{

  public GeoObjectActionQuery(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = componentQueryFactory.businessQuery(this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public GeoObjectActionQuery(com.runwaysdk.query.ValueQuery valueQuery)
  {
    super(valueQuery);
    if (this.getComponentQuery() == null)
    {
      com.runwaysdk.business.BusinessQuery businessQuery = new com.runwaysdk.business.BusinessQuery(valueQuery, this.getClassType());

       this.setBusinessQuery(businessQuery);
    }
  }

  public String getClassType()
  {
    return net.geoprism.registry.action.geoobject.GeoObjectAction.CLASS;
  }
  public com.runwaysdk.query.SelectableChar getGeoObjectCode()
  {
    return getGeoObjectCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode()
  {
    return getGeoObjectTypeCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOrganizationCode()
  {
    return getOrganizationCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getComponentQuery().get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, displayLabel);

  }
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  public com.runwaysdk.query.OIterator<? extends GeoObjectAction> getIterator()
  {
    this.checkNotUsedInValueQuery();
    String sqlStmt;
    if (_limit != null && _skip != null)
    {
      sqlStmt = this.getComponentQuery().getSQL(_limit, _skip);
    }
    else
    {
      sqlStmt = this.getComponentQuery().getSQL();
    }
    java.util.Map<String, com.runwaysdk.query.ColumnInfo> columnInfoMap = this.getComponentQuery().getColumnInfoMap();

    java.sql.ResultSet results = com.runwaysdk.dataaccess.database.Database.query(sqlStmt);
    return new com.runwaysdk.business.BusinessIterator<GeoObjectAction>(this.getComponentQuery().getMdEntityIF(), columnInfoMap, results);
  }


/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface GeoObjectActionQueryReferenceIF extends net.geoprism.registry.action.AbstractActionQuery.AbstractActionQueryReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getGeoObjectCode();
    public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias);
    public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode();
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias);
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOrganizationCode();
    public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias);
    public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias, String displayLabel);

    public com.runwaysdk.query.BasicCondition EQ(net.geoprism.registry.action.geoobject.GeoObjectAction geoObjectAction);

    public com.runwaysdk.query.BasicCondition NE(net.geoprism.registry.action.geoobject.GeoObjectAction geoObjectAction);

  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class GeoObjectActionQueryReference extends net.geoprism.registry.action.AbstractActionQuery.AbstractActionQueryReference
 implements GeoObjectActionQueryReferenceIF

  {

  public GeoObjectActionQueryReference(com.runwaysdk.dataaccess.MdAttributeRefDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }


    public com.runwaysdk.query.BasicCondition EQ(net.geoprism.registry.action.geoobject.GeoObjectAction geoObjectAction)
    {
      if(geoObjectAction == null) return this.EQ((java.lang.String)null);
      return this.EQ(geoObjectAction.getOid());
    }

    public com.runwaysdk.query.BasicCondition NE(net.geoprism.registry.action.geoobject.GeoObjectAction geoObjectAction)
    {
      if(geoObjectAction == null) return this.NE((java.lang.String)null);
      return this.NE(geoObjectAction.getOid());
    }

  public com.runwaysdk.query.SelectableChar getGeoObjectCode()
  {
    return getGeoObjectCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode()
  {
    return getGeoObjectTypeCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOrganizationCode()
  {
    return getOrganizationCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, displayLabel);

  }
  }

/**
 * Interface that masks all type unsafe query methods and defines all type safe methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public interface GeoObjectActionQueryMultiReferenceIF extends net.geoprism.registry.action.AbstractActionQuery.AbstractActionQueryMultiReferenceIF
  {

    public com.runwaysdk.query.SelectableChar getGeoObjectCode();
    public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias);
    public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode();
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias);
    public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias, String displayLabel);
    public com.runwaysdk.query.SelectableChar getOrganizationCode();
    public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias);
    public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias, String displayLabel);

    public com.runwaysdk.query.Condition containsAny(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction);
    public com.runwaysdk.query.Condition notContainsAny(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction);
    public com.runwaysdk.query.Condition containsAll(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction);
    public com.runwaysdk.query.Condition notContainsAll(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction);
    public com.runwaysdk.query.Condition containsExactly(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction);
  }

/**
 * Implements type safe query methods.
 * This type is used when a join is performed on this class as a reference.
 **/
  public static class GeoObjectActionQueryMultiReference extends net.geoprism.registry.action.AbstractActionQuery.AbstractActionQueryMultiReference
 implements GeoObjectActionQueryMultiReferenceIF

  {

  public GeoObjectActionQueryMultiReference(com.runwaysdk.dataaccess.MdAttributeMultiReferenceDAOIF mdAttributeIF, String attributeNamespace, String definingTableName, String definingTableAlias, String mdMultiReferenceTableName, com.runwaysdk.dataaccess.MdBusinessDAOIF referenceMdBusinessIF, String referenceTableAlias, com.runwaysdk.query.ComponentQuery rootQuery, java.util.Set<com.runwaysdk.query.Join> tableJoinSet, String alias, String displayLabel)
  {
    super(mdAttributeIF, attributeNamespace, definingTableName, definingTableAlias, mdMultiReferenceTableName, referenceMdBusinessIF, referenceTableAlias, rootQuery, tableJoinSet, alias, displayLabel);

  }



    public com.runwaysdk.query.Condition containsAny(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction)  {

      String[] itemIdArray = new String[geoObjectAction.length]; 

      for (int i=0; i<geoObjectAction.length; i++)
      {
        itemIdArray[i] = geoObjectAction[i].getOid();
      }

      return this.containsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAny(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction)  {

      String[] itemIdArray = new String[geoObjectAction.length]; 

      for (int i=0; i<geoObjectAction.length; i++)
      {
        itemIdArray[i] = geoObjectAction[i].getOid();
      }

      return this.notContainsAny(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsAll(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction)  {

      String[] itemIdArray = new String[geoObjectAction.length]; 

      for (int i=0; i<geoObjectAction.length; i++)
      {
        itemIdArray[i] = geoObjectAction[i].getOid();
      }

      return this.containsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition notContainsAll(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction)  {

      String[] itemIdArray = new String[geoObjectAction.length]; 

      for (int i=0; i<geoObjectAction.length; i++)
      {
        itemIdArray[i] = geoObjectAction[i].getOid();
      }

      return this.notContainsAll(itemIdArray);
  }

    public com.runwaysdk.query.Condition containsExactly(net.geoprism.registry.action.geoobject.GeoObjectAction ... geoObjectAction)  {

      String[] itemIdArray = new String[geoObjectAction.length]; 

      for (int i=0; i<geoObjectAction.length; i++)
      {
        itemIdArray[i] = geoObjectAction[i].getOid();
      }

      return this.containsExactly(itemIdArray);
  }
  public com.runwaysdk.query.SelectableChar getGeoObjectCode()
  {
    return getGeoObjectCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTCODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode()
  {
    return getGeoObjectTypeCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getGeoObjectTypeCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.GEOOBJECTTYPECODE, alias, displayLabel);

  }
  public com.runwaysdk.query.SelectableChar getOrganizationCode()
  {
    return getOrganizationCode(null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getOrganizationCode(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.get(net.geoprism.registry.action.geoobject.GeoObjectAction.ORGANIZATIONCODE, alias, displayLabel);

  }
  }
}
