package net.geoprism.registry.action.geoobject;

@com.runwaysdk.business.ClassSignature(hash = -1958254502)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to HierarchyValueOverTimeAttributeAction.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class HierarchyValueOverTimeAttributeActionQueryDTO extends net.geoprism.registry.action.geoobject.ValueOverTimeAttributeActionQueryDTO
{
private static final long serialVersionUID = -1958254502;

  protected HierarchyValueOverTimeAttributeActionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.action.geoobject.HierarchyValueOverTimeAttributeActionDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.action.geoobject.HierarchyValueOverTimeAttributeActionDTO>)super.getResultSet();
}
}
