package net.geoprism.registry.action.geoobject;

@com.runwaysdk.business.ClassSignature(hash = 1698691473)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to HierarchyValueOverTimeAttributeAction.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class HierarchyValueOverTimeAttributeActionBase extends net.geoprism.registry.action.geoobject.ValueOverTimeAttributeAction
{
  public final static String CLASS = "net.geoprism.registry.action.geoobject.HierarchyValueOverTimeAttributeAction";
  public static java.lang.String HIERARCHYCODE = "hierarchyCode";
  private static final long serialVersionUID = 1698691473;
  
  public HierarchyValueOverTimeAttributeActionBase()
  {
    super();
  }
  
  public String getHierarchyCode()
  {
    return getValue(HIERARCHYCODE);
  }
  
  public void validateHierarchyCode()
  {
    this.validateAttribute(HIERARCHYCODE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getHierarchyCodeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.action.geoobject.HierarchyValueOverTimeAttributeAction.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF)mdClassIF.definesAttribute(HIERARCHYCODE);
  }
  
  public void setHierarchyCode(String value)
  {
    if(value == null)
    {
      setValue(HIERARCHYCODE, "");
    }
    else
    {
      setValue(HIERARCHYCODE, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static HierarchyValueOverTimeAttributeActionQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    HierarchyValueOverTimeAttributeActionQuery query = new HierarchyValueOverTimeAttributeActionQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static HierarchyValueOverTimeAttributeAction get(String oid)
  {
    return (HierarchyValueOverTimeAttributeAction) com.runwaysdk.business.Business.get(oid);
  }
  
  public static HierarchyValueOverTimeAttributeAction getByKey(String key)
  {
    return (HierarchyValueOverTimeAttributeAction) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static HierarchyValueOverTimeAttributeAction lock(java.lang.String oid)
  {
    HierarchyValueOverTimeAttributeAction _instance = HierarchyValueOverTimeAttributeAction.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static HierarchyValueOverTimeAttributeAction unlock(java.lang.String oid)
  {
    HierarchyValueOverTimeAttributeAction _instance = HierarchyValueOverTimeAttributeAction.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
