package net.geoprism.registry.action.geoobject;

@com.runwaysdk.business.ClassSignature(hash = 1821977111)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ValueOverTimeAttributeAction.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ValueOverTimeAttributeActionQueryDTO extends net.geoprism.registry.action.geoobject.AttributeActionQueryDTO
{
private static final long serialVersionUID = 1821977111;

  protected ValueOverTimeAttributeActionQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.registry.action.geoobject.ValueOverTimeAttributeActionDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.registry.action.geoobject.ValueOverTimeAttributeActionDTO>)super.getResultSet();
}
}
